
name: deploy-bicep

on:
  repository_dispatch:
    types: [deploy]
  workflow_dispatch:
    

env:
  CLUSTER_NAME: clu-gitops
  RESOURCE_GROUP: rg-gitops-demo
  KEYVAULT: gebakv
  GITHUB_OWNER: gbaeke
  REPO: k8s-bootstrap


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.20.0
          inlineScript: |
            # Azure CLI 2.20 can deploy *.bicep files with az deployment group create
            az deployment group create -f ./bicep/deploy.bicep -g ${{ env.RESOURCE_GROUP }} --parameters ./bicep/deployparams.json