
name: deploy-bicep

on:
  repository_dispatch:
    types: [deploy]
  workflow_dispatch:
    

env:
  CLUSTER_NAME: clu-gitops
  RESOURCE_GROUP: rg-gitops-demo
  KEYVAULT: gebakv
  GITHUB_OWNER: gbaeke
  REPO: k8s-bootstrap


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Bicep build
        uses: aliencube/bicep-build-actions@v0.1
        with:
          files: bicep/deploy.bicep

      - name: Check the result
        shell: bash
        run: |
          shopt -s globstar
          ls -altR **/deploy*.*